---
- hosts: local
  connection: local
  vars_files: 
    - vars/main.yml
  tasks:

    - name: check if installer is already present
      stat: path="files/fcrepo-installer-{{fedora_version}}.jar"
      register: fcrepo_jar

    - name: Download Fedora from github releases
      get_url: url="https://github.com/fcrepo3/fcrepo/releases/download/v{{fedora_version}}/fcrepo-installer-{{fedora_version}}.jar" dest="files/fcrepo-installer-{{fedora_version}}.jar" sha256sum=f0fcde6cfd2ff8080a88f8c472fdf107df9a56ce2cbbd78d2e3c4db7480a4bdf
      when: fcrepo_jar.stat.exists == False

    - name: check if djatoka src is present
      stat: path="files/adore-djatoka-1.1.tar.gz"
      register: djatoka

    - name: Fetching Djatoka source into djatoka_home
      get_url: url="http://downloads.sourceforge.net/project/djatoka/djatoka/1.1/adore-djatoka-1.1.tar.gz" dest=files/ 
      when: djatoka.stat.exists == False

    - name: Check if Solr sources have been downloaded already
      stat: path="files/solr-{{solr_version}}"
      register: solr

    - name: Get Solr
      unarchive: copy=no dest="files/" src="http://archive.apache.org/dist/lucene/solr/{{solr_version}}/solr-{{solr_version}}.tgz"
      when: solr.stat.exists == False