---
- hosts: all
  vars_files: 
    - vars/main.yml
  become: true
  roles: 
    - common
  tasks:

    - name: Copy cached fcrepo to remote
      copy:
        src: files/fcrepo-installer-3.8.1.jar
        dest: /opt/fcrepo-installer-3.8.1.jar

    - name: check if installer is already present
      stat: path="/opt/fcrepo-installer-{{fedora_version}}.jar"
      register: fcrepo_jar

    - name: Download Fedora from github releases
      get_url: url="https://github.com/fcrepo3/fcrepo/releases/download/v{{fedora_version}}/fcrepo-installer-{{fedora_version}}.jar" dest="/opt/fcrepo-installer-{{fedora_version}}.jar" sha256sum=f0fcde6cfd2ff8080a88f8c472fdf107df9a56ce2cbbd78d2e3c4db7480a4bdf
      when: fcrepo_jar.stat.exists == False

    - name: Copy cached djatoka
      copy:
        src: files/adore-djatoka-1.1.tar.gz
        dest: /opt/adore-djatoka-1.1.tar.gz

    - name: check if djatoka src is present
      stat: path="/opt/adore-djatoka-1.1.tar.gz"
      register: djatoka

    - name: Fetching Djatoka source into djatoka_home
      get_url: url="http://downloads.sourceforge.net/project/djatoka/djatoka/1.1/adore-djatoka-1.1.tar.gz" dest=/opt/
      when: djatoka.stat.exists == False

    - name: get zip
      apt:
        name: zip
