---
# file: www.yml
- hosts: all
  vars_files: 
    - vars/www.yml
    - vars/main.yml
  roles:
    - common
    - geerlingguy.git
    - apache
    - geerlingguy.php
    - geerlingguy.composer
    - drush
    - drupal
    - islandora
    - drupal-cron
