---
## Leptonica
## configure vars in ../vars/main.yml

- name: create leptonica build dir
  file: path={{lept_dir}} state=directory

- stat: path="{{work_dir}}/{{lept_tar}}"
  register: lept_download

- name: fetch leptonica
  get_url: url="{{lept_url}}" dest="{{work_dir}}" force=no sha256sum="{{lept_sha}}"
  when: lept_download.stat.exists == False

- name: un-tar leptonica
  unarchive: copy=no src="{{work_dir}}/{{lept_tar}}" dest="{{work_dir}}"

- name: configure leptonica
  shell: ./configure
  args:
    chdir: "{{lept_dir}}"

- name: make and install leptonica
  shell: make && make install
  args:
    chdir: "{{lept_dir}}"

- name: "Remove working directory."
  file: path={{lept_dir}} state=absent

- name: "Remove source {{lept_tar}}."
  file: path="{{work_dir}}/{{lept_tar}}" state=absent

- template: src="../templates/{{lept_sem}}" dest={{semaphores_dir}} owner=ansible group=ansible mode=0644
