---
# http://tecadmin.net/install-oracle-java-8-jdk-8-ubuntu-via-ppa/

- name: install prereq for ansible apt_repository and for debconf
  apt:
    name: "{{ item }}"
  with_items:
    - python-apt
    - debconf
    - debconf-utils

- apt_repository: 
    repo: ppa:webupd8team/java
    validate_certs: no

- name: debconf accept license
  debconf:
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    value: true
    vtype: select

# there seems to be an issue here
####
#- name: debconf accept license
#  debconf:
#    name: oracle-java8-installer
#    question: shared/present-oracle-license-v1-1
#    value: true
#    vtype: seen

- shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections

- shell: echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections

- apt: 
    name: oracle-java8-installer
#    force: true

- shell: update-java-alternatives -s java-8-oracle

- apt: name=oracle-java8-set-default

- shell: readlink -f /usr/bin/java
  register: java_home

- lineinfile: 
    dest: /etc/environment 
    line: "JAVA_HOME={{java_home.stdout}}"
