---

#- name: Check if Solr sources have been downloaded already
#  stat: path="{{work_dir}}/solr-{{solr_version}}"
#  register: solr


- name: Get Solr
  copy: dest=/usr/local/ src="files/solr-{{solr_version}}/example/solr" owner=tomcat7 group=tomcat7

- name: copy solr.war into tomcat
  copy: dest="/var/lib/tomcat7/webapps/solr.war" src="files/solr-{{solr_version}}/dist/solr-{{solr_version}}.war" owner=tomcat7 group=tomcat7

- name: link solr to tomcat
  file: 
    src: "{{solr_home}}" 
    dest: /var/lib/tomcat7/
    state: link
    owner: tomcat7
    group: tomcat7

- name: Restart tomcat
  service: name=tomcat7 state=restarted