---
- name: Copy cached solr to /opt
  unarchive:
    src: files/solr.zip
    dest: /opt/
    owner: tomcat7
    group: tomcat7

- name: Check if Solr sources have been downloaded already
  stat: path="/opt/solr-{{solr_version}}"
  register: solr

- name: Get Solr
  unarchive:
    copy: no
    dest: "/opt/"
    src: "http://archive.apache.org/dist/lucene/solr/{{solr_version}}/solr-{{solr_version}}.tgz"
  when: solr.stat.exists == False

- name: Link Solr
  file: 
    dest: /usr/local/solr
    src: "/opt/solr-{{solr_version}}/example/solr"
    state: link
    owner: tomcat7
    group: tomcat7

- name: copy solr.war into tomcat
  copy: 
    dest: "/var/lib/tomcat7/webapps/solr.war"
    src: "/opt/solr-{{solr_version}}/dist/solr-{{solr_version}}.war"
    owner: tomcat7
    group: tomcat7
    remote_src: yes

- name: link solr to tomcat
  file: 
    src: "{{solr_home}}" 
    dest: /var/lib/tomcat7/solr
    state: link
    owner: tomcat7
    group: tomcat7

- name: Restart tomcat
  service:
    name: tomcat7
    state: restarted
