---

- name: copy httpd proxy settings into confs dir
  copy: 
    src: islandora.conf
    dest: /etc/apache2/conf-enabled/
  notify: 
    - restart apache

- service: 
    name: apache2
    state: restarted